Pagination
spo-iitk/ras-backend pull request #123
Opened 2023-06-25 04:38 UTC by Krishnansh5

- sending data in batches as described in frontend PR
- revoked APC access for inactive RCs

2023-06-26 06:05 UTC, abhishekshree submitted a review, later dismissed
lgtm

2023-06-26 06:05 UTC, abhishekshree commented
@Krishnansh5 document the rc/util.admin.go before merging

2023-06-26 06:40 UTC, 1-Harshit requested changes
Good PR, suggested some changes

2023-06-26 06:40 UTC, 1-Harshit commented on company/admin.get_company.go
> +	pageSizeInt, err := strconv.ParseInt(pageSize, 10, 32)
Don't we have util func for this?

2023-06-26 06:40 UTC, 1-Harshit commented on company/admin.get_company.go
> +	lastFetchedIdInt, err := strconv.ParseUint(lastFetchedId, 10, 32)
Again, util func?

2023-06-26 06:40 UTC, 1-Harshit commented on company/router.go
> +		admin.GET("/limited/:pageSize/:lastFetchedId", getLimitedCompaniesHandler)
I think we can have pagesize and lastpage page as query params instead of path params

2023-06-26 06:40 UTC, 1-Harshit commented on rc/util.admin.go
> +func ensurePseudoAdminAccess() gin.HandlerFunc {
Can you change file name to display it's a middleware? Also, ensurepsuedoadmin is already a function can you changed to something else? Like checkRCStatus? Or ensureActiveRC?

2023-06-26 06:40 UTC, 1-Harshit commented on student/router.go
> +		admin.GET("/limited", getLimitedStudentsHandler)
Limited? Pakka? 😂

2023-06-26 06:42 UTC, abhishekshree commented
@1-Harshit full nitpicking i see i see

2023-06-26 06:48 UTC, 1-Harshit commented
Left some 'suggestions' is all :)
Won't do if you're so against it.

2023-06-26 06:50 UTC, abhishekshree commented
Nahi bhai teri bhi repo hai

2023-07-06 20:42 UTC, merged

2023-08-09 09:25 UTC, utkarsh-tf141 commented
-closes #100 #102