Add delete button and UnRecruit logic
spo-iitk/ras-backend pull request #142
Opened 2023-09-06 00:13 UTC by qu-bit1

- Deletes students from an event (Delete all & delete individually)
- Implemented UnRecruit logic in both the delete functions

2023-09-06 00:15 UTC, qu-bit1 commented
fixing linting issues

2023-09-06 04:46 UTC, 1-Harshit requested changes
This is not right flow, try to make one api EXACTLY INVERSE of register student api. For consistency and readability.

2023-09-06 04:46 UTC, 1-Harshit commented on application/admin.student.go
> +	if err = rc.UnRecruitStudent(ctx, studentID, rcID); err != nil {
What?

2023-12-25 08:05 UTC, 1-Harshit commented on application/admin.student.go
> +	if err = rc.UnRecruitStudent(ctx, studentID, rcID); err != nil {
this should only be invoked if the event is "Recruited" or "PPO" right?

2023-12-25 17:46 UTC, qu-bit1 commented on application/admin.student.go
> +	if err = rc.UnRecruitStudent(ctx, studentID, rcID); err != nil {
yes fixing that and a few more things

2024-01-20 16:59 UTC, merged